title: Henrique Franzener Hyppolito
logo: assets/img/Perfil.png
description: Structural Engineer | BIM manager 
description2: >
    Skilled Civil Engineer with over four years of experience in designing concrete and steel structures.
    I have always been committed to deliver smart and more efficient solutions no matter the project scale.
show_downloads: true
theme: jekyll-theme-minimal
