title: Henrique Franzener Hyppolito
logo: assets/img/Perfil.png
description: Structural Engineer | BIM manager 
description2: |+
    Skilled Structural Engineer with over five years of experience designing concrete and steel structures. 
    Advanced level of knowledge in BIM (coordinating, modeling and developing API for Revit).
    I have always been committed to deliver smart and more efficient solutions no matter the project scale.
show_downloads: true
theme: jekyll-theme-minimal
